### ISSUE TITLE
Make the extension up to date

### ISSUE THREAD

**Issue by thiagoa** [brpaz/ulauncher-chrome-tabs#11]
When trying to install the extension, I had a few issues:

- The hardcoded native messaging implementation from the `host` file was not working for some reason. 
- `python-websocket-server` (or dependencies) seems to have changed something under the hood. The `on_ws_error` callback was no longer working with the latest version.
- At least in Ubuntu 20.04, there seems to be no `python` executable. I found `python3` though.

I came up with a fix to make the extension work for me, which can be found in this commit:

https://github.com/thiagoa/ulauncher-chrome-tabs/commit/45014b218bd97cb5c5a2c5752db582150cab159d

I'm using the `nativemessaging` library since it works out of the box.

@brpaz Do you have any interest in this code? I could improve it if so and invest more time into making the solution more general.

Regarding the `host` file, I'm having problems with the logger (`logging` library). I can't get it to log anything :( The only way I could make logging work was to open a file in append mode, write to it and call `flush` right away. I haven't changed the code for logging though.

**Comment by brpaz** [comment]
Hello. 
Yes, this extension is unmaintained for some time as it is kinda complex to set up, and also I am not using Chrome as my primary browser.

Today I stumbled upon [this](https://github.com/balta2ar/brotab), and I thought it could be a better option to build an Ulauncher extension for it, as the Native Messaging part would be handled by Brotab and Ulauncher could be just a frontend to the command line tool. 

Also It has support for Firefox and Brave Browser.

I will need to see if it works fine though.

**Comment by thiagoa** [comment]
@brpaz Interesting! I gave it a quick test and it works indeed, with both Chrome and Firefox at the same time. Listed clients, listed tabs, opened tabs, etc. Much easier to setup and would give a great extension. Thanks for the tip.

I'm glad I could make your very useful extension up to date and work for me though.

**Comment by brpaz** [comment]
@thiagoa just build a basic extension for Brotab [here](https://github.com/brpaz/ulauncher-brotab) ;)
